seed: 42
n_trials: 100
horizon: 50000
task: trim
methods:
  - GoTrim
  - AdaptiveGoTrim
folder: exp_trim
data: arange
n: 500
outlier: 10
shuffle: true
eps: 0.3
graph: Watts-Strogatz
alpha: 0.4
rank: GoRankAsync
verbose: false
sampling: async
